<?php

namespace App\Dao\MySQL\mfsdevsystemManagerStore;
use App\Models\PesquisaModel;

class PesquisaDao extends Connection {

    private $pesquisaDAO;

    public function __construct()
    {
        parent:: __construct();
    }
    
    public function getAllPesquisas():array
    {
       $pesquisas = $this->pdo
           ->query("SELECT * 
                      FROM pesquisa_atendimento
                      WHERE isDeleted = '0';")
           ->fetchAll(\PDO::FETCH_ASSOC);

       return $pesquisas;
    }

   
    public function insertPesquisa(PesquisaModel $pesquisa): void
    {
       //echo '<pre>';
       //var_dump($pesquisa);
       //die;

       $sql = 'INSERT INTO pesquisa_atendimento (
        usuario_id,
        hasBandaLarga,
        bandaLargaFornecedor,
        bandaLargaVelocidade,
        bandaLargaValor,
        hasLinkDedicado,
        linkDedicadoFornecedor,
        linkDedicadoVelocidade,
        linkDedicadoValor,
        hasLinhaFixa,
        linhaFixaFornecedor,
        linhaFixaVelocidade,
        linhaFixaValor,
        hasPabx,
        pabxFornecedor,
        pabxVelocidade,
        pabxValor,
        hasSdwan,
        sdwanFornecedor,
        sdwanVelocidade,
        sdwanValor,
        hasGestaoTrafego,
        gestaoTrafegoFornecedor,
        gestaoTrafegoVelocidade,
        gestaoTrafegoValor,
        hasDesktop,
        desktopFornecedor,
        desktopVelocidade,
        desktopValor,
        hasNotebook,
        notebookFornecedor,
        notebookVelocidade,
        notebookValor,
        hasOffice365,
        office365Fornecedor,
        office365Velocidade,
        office365Valor,
        hasGoogleWorkspace,
        googleWorkspaceFornecedor,
        googleWorkspaceVelocidade,
        googleWorkspaceValor,
        hasCloud,
        cloudFornecedor,
        cloudVelocidade,
        cloudValor,
        hasServidor,
        servidorFornecedor,
        servidorVelocidade,
        servidorValor,
        hasSite,
        siteUrl,
        hasInstagram,
        instagramUrl,
        hasLinkedin,
        linkedinUrl,
        hasEspecialista,
        especialista,
        dataAgendamento,
        valorTotal,
        isDeleted,
        created_at,
        updated_at
    ) VALUES (
        :usuarioId,
        :hasBandaLarga,
        :bandaLargaFornecedor,
        :bandaLargaVelocidade,
        :bandaLargaValor,
        :hasLinkDedicado,
        :linkDedicadoFornecedor,
        :linkDedicadoVelocidade,
        :linkDedicadoValor,
        :hasLinhaFixa,
        :linhaFixaFornecedor,
        :linhaFixaVelocidade,
        :linhaFixaValor,
        :hasPabx,
        :pabxFornecedor,
        :pabxVelocidade,
        :pabxValor,
        :hasSdwan,
        :sdwanFornecedor,
        :sdwanVelocidade,
        :sdwanValor,
        :hasGestaoTrafego,
        :gestaoTrafegoFornecedor,
        :gestaoTrafegoVelocidade,
        :gestaoTrafegoValor,
        :hasDesktop,
        :desktopFornecedor,
        :desktopVelocidade,
        :desktopValor,
        :hasNotebook,
        :notebookFornecedor,
        :notebookVelocidade,
        :notebookValor,
        :hasOffice365,
        :office365Fornecedor,
        :office365Velocidade,
        :office365Valor,
        :hasGoogleWorkspace,
        :googleWorkspaceFornecedor,
        :googleWorkspaceVelocidade,
        :googleWorkspaceValor,
        :hasCloud,
        :cloudFornecedor,
        :cloudVelocidade,
        :cloudValor,
        :hasServidor,
        :servidorFornecedor,
        :servidorVelocidade,
        :servidorValor,
        :hasSite,
        :siteUrl,
        :hasInstagram,
        :instagramUrl,
        :hasLinkedin,
        :linkedinUrl,
        :hasEspecialista,
        :especialista,
        :dataAgendamento,
        :valorTotal,
        :isDeleted,
        :createdAt,
        :updatedAt
    );';
 
     $statement = $this->pdo->prepare($sql);
 
     $statement->execute([
         'usuarioId' => $pesquisa->getUsuarioId(),
         'hasBandaLarga' => $pesquisa->getHasBandaLarga(),
         'bandaLargaFornecedor' => $pesquisa->getBandaLargaFornecedor(),
         'bandaLargaVelocidade' => $pesquisa->getBandaLargaVelocidade(),
         'bandaLargaValor' => $pesquisa->getBandaLargaValor(),
         'hasLinkDedicado' => $pesquisa->getHasLinkDedicado(),
         'linkDedicadoFornecedor' => $pesquisa->getLinkDedicadoFornecedor(),
         'linkDedicadoVelocidade' => $pesquisa->getLinkDedicadoVelocidade(),
         'linkDedicadoValor' => $pesquisa->getLinkDedicadoValor(),
         'hasLinhaFixa' => $pesquisa->getHasLinhaFixa(),
         'linhaFixaFornecedor' => $pesquisa->getLinhaFixaFornecedor(),
         'linhaFixaVelocidade' => $pesquisa->getLinhaFixaVelocidade(),
         'linhaFixaValor' => $pesquisa->getLinhaFixaValor(),
         'hasPabx' => $pesquisa->getHasPabx(),
         'pabxFornecedor' => $pesquisa->getPabxFornecedor(),
         'pabxVelocidade' => $pesquisa->getPabxVelocidade(),
         'pabxValor' => $pesquisa->getPabxValor(),
         'hasSdwan' => $pesquisa->getHasSdwan(),
         'sdwanFornecedor' => $pesquisa->getSdwanFornecedor(),
         'sdwanVelocidade' => $pesquisa->getSdwanVelocidade(),
         'sdwanValor' => $pesquisa->getSdwanValor(),
         'hasGestaoTrafego' => $pesquisa->getHasGestaoTrafego(),
         'gestaoTrafegoFornecedor' => $pesquisa->getGestaoTrafegoFornecedor(),
         'gestaoTrafegoVelocidade' => $pesquisa->getGestaoTrafegoVelocidade(),
         'gestaoTrafegoValor' => $pesquisa->getGestaoTrafegoValor(),
         'hasDesktop' => $pesquisa->getHasDesktop(),
         'desktopFornecedor' => $pesquisa->getDesktopFornecedor(),
         'desktopVelocidade' => $pesquisa->getDesktopVelocidade(),
         'desktopValor' => $pesquisa->getDesktopValor(),
         'hasNotebook' => $pesquisa->getHasNotebook(),
         'notebookFornecedor' => $pesquisa->getNotebookFornecedor(),
         'notebookVelocidade' => $pesquisa->getNotebookVelocidade(),
         'notebookValor' => $pesquisa->getNotebookValor(),
         'hasOffice365' => $pesquisa->getHasOffice365(),
         'office365Fornecedor' => $pesquisa->getOffice365Fornecedor(),
         'office365Velocidade' => $pesquisa->getOffice365Velocidade(),
         'office365Valor' => $pesquisa->getOffice365Valor(),
         'hasGoogleWorkspace' => $pesquisa->getHasGoogleWorkspace(),
         'googleWorkspaceFornecedor' => $pesquisa->getGoogleWorkspaceFornecedor(),
         'googleWorkspaceVelocidade' => $pesquisa->getGoogleWorkspaceVelocidade(),
         'googleWorkspaceValor' => $pesquisa->getGoogleWorkspaceValor(),
         'hasCloud' => $pesquisa->getHasCloud(),
         'cloudFornecedor' => $pesquisa->getCloudFornecedor(),
         'cloudVelocidade' => $pesquisa->getCloudVelocidade(),
         'cloudValor' => $pesquisa->getCloudValor(),
         'hasServidor' => $pesquisa->getHasServidor(),
         'servidorFornecedor' => $pesquisa->getServidorFornecedor(),
         'servidorVelocidade' => $pesquisa->getServidorVelocidade(),
         'servidorValor' => $pesquisa->getServidorValor(),
         'hasSite' => $pesquisa->getHasSite(),
         'siteUrl' => $pesquisa->getSiteUrl(),
         'hasInstagram' => $pesquisa->getHasInstagram(),
         'instagramUrl' => $pesquisa->getInstagramUrl(),
         'hasLinkedin' => $pesquisa->getHasLinkedin(),
         'linkedinUrl' => $pesquisa->getLinkedinUrl(),
         'hasEspecialista' => $pesquisa->getHasEspecialista(),
         'especialista' => $pesquisa->getEspecialista(),
         'dataAgendamento' => $pesquisa->getDataAgendamento() ? $pesquisa->getDataAgendamento()->format('Y-m-d H:i:s') : null,
         'valorTotal' => $pesquisa->getValorTotal(),
         'isDeleted' => $pesquisa->getIsDeleted(),
         'createdAt' => $pesquisa->getCreatedAt()->format('Y-m-d H:i:s'),
         'updatedAt' => $pesquisa->getUpdatedAt()->format('Y-m-d H:i:s'),
     ]);

    }

    public function updatePesquisa(PesquisaModel $pesquisa): void
    {
        
    $sql = 'UPDATE pesquisa_atendimento SET
        usuario_id = :usuarioId,
        hasBandaLarga = :hasBandaLarga,
        bandaLargaFornecedor = :bandaLargaFornecedor,
        bandaLargaVelocidade = :bandaLargaVelocidade,
        bandaLargaValor = :bandaLargaValor,
        hasLinkDedicado = :hasLinkDedicado,
        linkDedicadoFornecedor = :linkDedicadoFornecedor,
        linkDedicadoVelocidade = :linkDedicadoVelocidade,
        linkDedicadoValor = :linkDedicadoValor,
        hasLinhaFixa = :hasLinhaFixa,
        linhaFixaFornecedor = :linhaFixaFornecedor,
        linhaFixaVelocidade = :linhaFixaVelocidade,
        linhaFixaValor = :linhaFixaValor,
        hasPabx = :hasPabx,
        pabxFornecedor = :pabxFornecedor,
        pabxVelocidade = :pabxVelocidade,
        pabxValor = :pabxValor,
        hasSdwan = :hasSdwan,
        sdwanFornecedor = :sdwanFornecedor,
        sdwanVelocidade = :sdwanVelocidade,
        sdwanValor = :sdwanValor,
        hasGestaoTrafego = :hasGestaoTrafego,
        gestaoTrafegoFornecedor = :gestaoTrafegoFornecedor,
        gestaoTrafegoVelocidade = :gestaoTrafegoVelocidade,
        gestaoTrafegoValor = :gestaoTrafegoValor,
        hasDesktop = :hasDesktop,
        desktopFornecedor = :desktopFornecedor,
        desktopVelocidade = :desktopVelocidade,
        desktopValor = :desktopValor,
        hasNotebook = :hasNotebook,
        notebookFornecedor = :notebookFornecedor,
        notebookVelocidade = :notebookVelocidade,
        notebookValor = :notebookValor,
        hasOffice365 = :hasOffice365,
        office365Fornecedor = :office365Fornecedor,
        office365Velocidade = :office365Velocidade,
        office365Valor = :office365Valor,
        hasGoogleWorkspace = :hasGoogleWorkspace,
        googleWorkspaceFornecedor = :googleWorkspaceFornecedor,
        googleWorkspaceVelocidade = :googleWorkspaceVelocidade,
        googleWorkspaceValor = :googleWorkspaceValor,
        hasCloud = :hasCloud,
        cloudFornecedor = :cloudFornecedor,
        cloudVelocidade = :cloudVelocidade,
        cloudValor = :cloudValor,
        hasServidor = :hasServidor,
        servidorFornecedor = :servidorFornecedor,
        servidorVelocidade = :servidorVelocidade,
        servidorValor = :servidorValor,
        hasSite = :hasSite,
        siteUrl = :siteUrl,
        hasInstagram = :hasInstagram,
        instagramUrl = :instagramUrl,
        hasLinkedin = :hasLinkedin,
        linkedinUrl = :linkedinUrl,
        hasEspecialista = :hasEspecialista,
        especialista = :especialista,
        dataAgendamento = :dataAgendamento,
        valorTotal = :valorTotal,
        isDeleted = :isDeleted,
        updated_at = :updatedAt
    WHERE id = :id';

    $statement = $this->pdo->prepare($sql);

    $statement->execute([
        'id' => $pesquisa->getId(),
        'usuarioId' => $pesquisa->getUsuarioId(),
        'hasBandaLarga' => $pesquisa->getHasBandaLarga(),
        'bandaLargaFornecedor' => $pesquisa->getBandaLargaFornecedor(),
        'bandaLargaVelocidade' => $pesquisa->getBandaLargaVelocidade(),
        'bandaLargaValor' => $pesquisa->getBandaLargaValor(),
        'hasLinkDedicado' => $pesquisa->getHasLinkDedicado(),
        'linkDedicadoFornecedor' => $pesquisa->getLinkDedicadoFornecedor(),
        'linkDedicadoVelocidade' => $pesquisa->getLinkDedicadoVelocidade(),
        'linkDedicadoValor' => $pesquisa->getLinkDedicadoValor(),
        'hasLinhaFixa' => $pesquisa->getHasLinhaFixa(),
        'linhaFixaFornecedor' => $pesquisa->getLinhaFixaFornecedor(),
        'linhaFixaVelocidade' => $pesquisa->getLinhaFixaVelocidade(),
        'linhaFixaValor' => $pesquisa->getLinhaFixaValor(),
        'hasPabx' => $pesquisa->getHasPabx(),
        'pabxFornecedor' => $pesquisa->getPabxFornecedor(),
        'pabxVelocidade' => $pesquisa->getPabxVelocidade(),
        'pabxValor' => $pesquisa->getPabxValor(),
        'hasSdwan' => $pesquisa->getHasSdwan(),
        'sdwanFornecedor' => $pesquisa->getSdwanFornecedor(),
        'sdwanVelocidade' => $pesquisa->getSdwanVelocidade(),
        'sdwanValor' => $pesquisa->getSdwanValor(),
        'hasGestaoTrafego' => $pesquisa->getHasGestaoTrafego(),
        'gestaoTrafegoFornecedor' => $pesquisa->getGestaoTrafegoFornecedor(),
        'gestaoTrafegoVelocidade' => $pesquisa->getGestaoTrafegoVelocidade(),
        'gestaoTrafegoValor' => $pesquisa->getGestaoTrafegoValor(),
        'hasDesktop' => $pesquisa->getHasDesktop(),
        'desktopFornecedor' => $pesquisa->getDesktopFornecedor(),
        'desktopVelocidade' => $pesquisa->getDesktopVelocidade(),
        'desktopValor' => $pesquisa->getDesktopValor(),
        'hasNotebook' => $pesquisa->getHasNotebook(),
        'notebookFornecedor' => $pesquisa->getNotebookFornecedor(),
        'notebookVelocidade' => $pesquisa->getNotebookVelocidade(),
        'notebookValor' => $pesquisa->getNotebookValor(),
        'hasOffice365' => $pesquisa->getHasOffice365(),
        'office365Fornecedor' => $pesquisa->getOffice365Fornecedor(),
        'office365Velocidade' => $pesquisa->getOffice365Velocidade(),
        'office365Valor' => $pesquisa->getOffice365Valor(),
        'hasGoogleWorkspace' => $pesquisa->getHasGoogleWorkspace(),
        'googleWorkspaceFornecedor' => $pesquisa->getGoogleWorkspaceFornecedor(),
        'googleWorkspaceVelocidade' => $pesquisa->getGoogleWorkspaceVelocidade(),
        'googleWorkspaceValor' => $pesquisa->getGoogleWorkspaceValor(),
        'hasCloud' => $pesquisa->getHasCloud(),
        'cloudFornecedor' => $pesquisa->getCloudFornecedor(),
        'cloudVelocidade' => $pesquisa->getCloudVelocidade(),
        'cloudValor' => $pesquisa->getCloudValor(),
        'hasServidor' => $pesquisa->getHasServidor(),
        'servidorFornecedor' => $pesquisa->getServidorFornecedor(),
        'servidorVelocidade' => $pesquisa->getServidorVelocidade(),
        'servidorValor' => $pesquisa->getServidorValor(),
        'hasSite' => $pesquisa->getHasSite(),
        'siteUrl' => $pesquisa->getSiteUrl(),
        'hasInstagram' => $pesquisa->getHasInstagram(),
        'instagramUrl' => $pesquisa->getInstagramUrl(),
        'hasLinkedin' => $pesquisa->getHasLinkedin(),
        'linkedinUrl' => $pesquisa->getLinkedinUrl(),
        'hasEspecialista' => $pesquisa->getHasEspecialista(),
        'especialista' => $pesquisa->getEspecialista(),
        'dataAgendamento' => $pesquisa->getDataAgendamento() ? $pesquisa->getDataAgendamento()->format('Y-m-d H:i:s') : null,
        'valorTotal' => $pesquisa->getValorTotal(),
        'isDeleted' => $pesquisa->getIsDeleted(),
        'updatedAt' => $pesquisa->getUpdatedAt()->format('Y-m-d H:i:s'),
     ]);
    }
}       