<?php

putenv('DISPLAY_ERRORS_DETAILS='.false);
putenv('DB_MSGESTOR_MYSQL_DRIVER=mysql');
putenv('DB_MSGESTOR_MYSQL_HOST=');
putenv('DB_MSGESTOR_MYSQL_PORT=');
putenv('DB_MSGESTOR_MYSQL_DBNAME=');
putenv('DB_MSGESTOR_MYSQL_USER=');
putenv('DB_MSGESTOR_MYSQL_PASSWORD=');

putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_DRIVER=mysql');
putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_HOST=');
putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_PORT=');
putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_DBNAME=');
putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_USER=');
putenv('MFSDEVSYSTEM_MANAGER_STORE_MYSQL_PASSWORD=');